### ISSUE TITLE
Error while building SlicerSALT in docker

### ISSUE THREAD

**Issue by lopezmt** [Kitware/SlicerSALT#142]
hi, 

I am trying to build SlicerSALT using the qt5-centos7 Slicer build environment Docker file but the compilation ends with errors. The errors occur while building SRep.

@jcfr, @phcerdan, do you know what could be the problem?

Here is the error I got:

```
[ 74%] Building CXX object E/SRep/SkeletalRepresentationInitializer/Logic/CMakeFiles/vtkSlicerSkeletalRepresentationInitializerModuleLogicPythonD.dir/vtkBackwardFlowLogicPython.cxx.o

/osm_qSlicerUnitsModuleWidgets_module_init.cpp.o
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx: In function ‘PyObject* PyvtkBackwardFlowLogic_runApplyTPS(PyObject*, PyObject*)’:
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx:25:68: error: invalid static_cast from type ‘vtkObjectBase*’ to type ‘vtkBackwardFlowLogic*’
   vtkBackwardFlowLogic *op = static_cast<vtkBackwardFlowLogic *>(vp);
                                                                    ^
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx: In function ‘PyObject* PyvtkBackwardFlowLogic_computePairwiseTPS(PyObject*, PyObject*)’:
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx:55:68: error: invalid static_cast from type ‘vtkObjectBase*’ to type ‘vtkBackwardFlowLogic*’
   vtkBackwardFlowLogic *op = static_cast<vtkBackwardFlowLogic *>(vp);
                                                                    ^
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx: In function ‘PyObject* PyvtkBackwardFlowLogic_generateEllipsoidSrep(PyObject*, PyObject*)’:
/NIRAL/work/lpzmateo/source/Projects/SlicerSALT-build/Slicer-build/E/SRep/SkeletalRepresentationInitializer/Logic/vtkBackwardFlowLogicPython.cxx:91:68: error: invalid static_cast from type ‘vtkObjectBase*’ to type ‘vtkBackwardFlowLogic*’
   vtkBackwardFlowLogic *op = static_cast<vtkBackwardFlowLogic *>(vp);
                                                                    ^
make[5]: *** [E/SRep/SkeletalRepresentationInitializer/Logic/CMakeFiles/vtkSlicerSkeletalRepresentationInitializerModuleLogicPythonD.dir/vtkBackwardFlowLogicPython.cxx.o] Error 1
make[4]: *** [E/SRep/SkeletalRepresentationInitializer/Logic/CMakeFiles/vtkSlicerSkeletalRepresentationInitializerModuleLogicPythonD.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [slicersources-build/Slicer-prefix/src/Slicer-stamp/Slicer-build] Error 2
make[1]: *** [slicersources-build/CMakeFiles/Slicer.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jcfr** [comment]
Thanks for reporting the issue.

Could you share the command used to configure and build the project ?

Worth noting that the daily linux build done with the docker image seems to [succeed](https://open.cdash.org/index.php?project=SlicerSALT&date=2019-03-01). This is one done on metroplex.

For reference, corresponding build script can be found [here](https://github.com/Slicer/DashboardScripts/blob/7da4c579dd29f00d5bd121cd2264de2094c3db86/metroplex.sh#L60-L76)

**Comment by phcerdan** [comment]
Thanks @lopezmt.
I cannot reproduce it locally in my machine. It seems like that Python.cxx file is not finding, or not linking to the library where vtkBackwardFlowLogic is defined?

Is that a clean build?

**Comment by lopezmt** [comment]
I used the commands described in the ReadMe:
```
mkdir SlicerSALT-build
cd SlicerSALT-build
ccmake ../SlicerSALT-build
```

at this point, I have set the Slicer_REQUIRED_QT_VERSION variable to 5.11.2 instead of 4.7.4
and finally, 

`make -j4`

**Comment by lopezmt** [comment]
I am going to try again to be sure.

**Comment by jcfr** [comment]
Could you also share how you make use of the docker image ?

**Comment by lopezmt** [comment]
The image was already present in the docker server of the lab, I used this command to create the container:

`docker container run -it --name lpz_SlicerSALT -v /work/lpzmateo:/work/lpzmateo slicer/buildenv-qt5-centos7 bash` 

I realize that I should have used the 'latest' tag after the image name, do you think that could be the problem?

**Comment by jcfr** [comment]
To streamline use of the image, I would recommend to do this instead:

```
docker run --rm slicer/buildenv-qt5-centos7:latest > ~/bin/slicer-buildenv-qt5-centos7-latest
chmod ~/bin/slicer-buildenv-qt5-centos7-latest
```

Then, assuming `~/bin` in the `PATH`, you could simply do this:

```
mkdir /work/lpzmateo/SlicerSALT
cd /work/lpzmateo/SlicerSALT
git clone https://github.com/kitware/SlicerSALT
```

Then, you could either directly configure and build doing:

```
slicer-buildenv-qt5-centos7-latest cmake -H SlicerSALT -B SlicerSALT-build -GNinja
slicer-buildenv-qt5-centos7-latest cmake --build SlicerSALT-build
```

Or start a shell, and then build/configure/etc ... 

```
cd /work/lpzmateo/SlicerSALT
slicer-buildenv-qt5-centos7-latest bash
```

and the usual

```
mkdir /work/SlicerSALT-build
cmake -G Ninja ../SlicerSALT
ninja
```

### Notes

* The script `slicer-buildenv-qt5-centos7-latest`:
  * takes care of mounting the current directory 
  * provide subcommand allowing to update the image and the script itself (try `slicer-buildenv-qt5-centos7-latest -h`

**Comment by lopezmt** [comment]
Thank you for your help! Using a script instead of the usual command line is definitely a good idea.
SlicerSALT is building, I will let you know if it works.

**Comment by lopezmt** [comment]
After following your method, I end up with the same issue, here are the exact commands I used : 

```
mkdir SlicerSALT
cd SlicerSALT/
git clone https://github.com/kitware/SlicerSALT
slicer-buildenv-qt5-centos7-latest cmake -HSlicerSALT -BSlicerSALT-build -GNinja -DSlicer_REQUIRED_QT_VERSION=5.11.2
slicer-buildenv-qt5-centos7-latest cmake --build SlicerSALT-build
```

I don't understand what is the problem, if the daily Linux build is working I should not have any problem using this method. maybe there is a problem with our docker image?

**Comment by lopezmt** [comment]
it doesn't on my own computer either, I built the docker image and tried the steps but it ends with the same result.

**Comment by jcfr** [comment]
Hi Mateo,

I suggest we do a video hangout. Would be available tomorrow ?

Jc

**Comment by lopezmt** [comment]
Hi Jc,

Sure, I am available after 11am.

Mateo

**Comment by jcfr** [comment]
To follow up, I just schedule a meeting for 1pm, you should have get an invite.

**Comment by jcfr** [comment]
@lopezmt and I had a chance to discuss. 

Here is a summary:
* docker image was most likely out of data. Running `docker pull slicer/buildenv-qt5-centos7` or `slicer-buildenv-qt5-centos7-latest update` ensure the latest version is used.
* we fixed the docker installation to allow running docker without being root user. See [here](https://medium.com/devgorilla/how-to-install-docker-on-ubuntu-18-04-495216a16092)
* reviewed how the mounting of the external hard-drive with NTFS partition could be done with user `mateo` instead of `root`. The idea is to specify `uid` in `/etc/fstab`. See [here](https://askubuntu.com/questions/113733/how-do-i-correctly-mount-a-ntfs-partition-in-etc-fstab#113746).

**Comment by jcfr** [comment]
@lopezmt To follow up on our last discussion, do you still have issues ? If not, I suggest we close this issue.

**Comment by lopezmt** [comment]
Hi @jcfr,

after some tries and checks, I keep getting the same error...

This is the digest of the image I am using, can you tell me if we have the same one?

```
Using default tag: latest
latest: Pulling from slicer/buildenv-qt5-centos7
Digest: sha256:73551960143845b5f93a4d3f9a7d5fbcacd545a1ef42b6dfbf49746405baa78a
Status: Image is up to date for slicer/buildenv-qt5-centos7:latest
```

**Comment by bpaniagua** [comment]
HI @lopezmt, were you able to resolve this problem? 
Thanks,
Bea

**Comment by lopezmt** [comment]
Hi  @bpaniagua,
I still have the same problem but Juan is trying to compile a version of SlicerSALT that I will be able to use to start working on the data importer.
Thanks,
Mateo

**Comment by lopezmt** [comment]
Hi, we finally manage to build SlicerSALT but we had to modify the code of SRep.
In the header file vtkBackwardFlowLogic.h, we modified the declaration of the class vtkBackwardFlowLogic so it inherits from vtkObjectBase, it solved the casting issue.

I don't know if this was the best way to solve this issue and I still don't understand why you don't have the problem while building SlicerSALT in docker but I can finally launch it!

Do you think I can close this issue?

Thanks,
Mateo

**Comment by bpaniagua** [comment]
HI Mateo,


Great job! Lets wait for @jcfr to be back from vacation on Monday. We might have to open another issue to resolve the casting problem you found. 

Thank you!
Bea

**Comment by phcerdan** [comment]
Hi @lopezmt, could you open an issue in SRep: https://github.com/KitwareMedical/SlicerSkeletalRepresentation/issues ?

The more steps for reproducing it, the better.
And also, please post the solution that you came up with.
Thanks!

**Comment by lopezmt** [comment]
Hi @phcerdan, no problem I will open the issue

Thanks!

**Comment by phcerdan** [comment]
Thanks for the detailed report in https://github.com/KitwareMedical/SlicerSkeletalRepresentation/issues/20
and the PR in: https://github.com/KitwareMedical/SlicerSkeletalRepresentation/pull/22 :1st_place_medal:
